"""Initial migration from schema

Revision ID: 936ca3bfdc87
Revises: 
Create Date: 2025-11-12 16:30:32.622979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936ca3bfdc87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advanced_match_stats',
    sa.Column('stat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('xg_against', sa.Float(), nullable=True),
    sa.Column('xa', sa.Float(), nullable=True),
    sa.Column('npxg', sa.Float(), nullable=True),
    sa.Column('progressive_passes', sa.Integer(), nullable=True),
    sa.Column('progressive_carries', sa.Integer(), nullable=True),
    sa.Column('progressive_pass_distance', sa.Float(), nullable=True),
    sa.Column('pressures', sa.Integer(), nullable=True),
    sa.Column('pressure_success_rate', sa.Float(), nullable=True),
    sa.Column('pressures_att_third', sa.Integer(), nullable=True),
    sa.Column('pressures_mid_third', sa.Integer(), nullable=True),
    sa.Column('pressures_def_third', sa.Integer(), nullable=True),
    sa.Column('through_balls', sa.Integer(), nullable=True),
    sa.Column('switches', sa.Integer(), nullable=True),
    sa.Column('ground_passes', sa.Integer(), nullable=True),
    sa.Column('low_passes', sa.Integer(), nullable=True),
    sa.Column('high_passes', sa.Integer(), nullable=True),
    sa.Column('shot_creating_actions', sa.Integer(), nullable=True),
    sa.Column('goal_creating_actions', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('stat_id'),
    sa.UniqueConstraint('match_id', 'team_id', 'source', name='uq_advanced_match_stats_match_team_source')
    )
    op.create_index('idx_advanced_stats_match', 'advanced_match_stats', ['match_id'], unique=False)
    op.create_index('idx_advanced_stats_team', 'advanced_match_stats', ['team_id'], unique=False)
    op.create_table('player_match_stats',
    sa.Column('stat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('penalties_scored', sa.Integer(), nullable=True),
    sa.Column('penalties_attempted', sa.Integer(), nullable=True),
    sa.Column('shots_total', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('passes_total', sa.Integer(), nullable=True),
    sa.Column('passes_completed', sa.Integer(), nullable=True),
    sa.Column('pass_accuracy_percent', sa.Float(), nullable=True),
    sa.Column('key_passes', sa.Integer(), nullable=True),
    sa.Column('tackles_total', sa.Integer(), nullable=True),
    sa.Column('tackles_won', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('clearances', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('fouls_committed', sa.Integer(), nullable=True),
    sa.Column('fouls_drawn', sa.Integer(), nullable=True),
    sa.Column('offsides', sa.Integer(), nullable=True),
    sa.Column('crosses', sa.Integer(), nullable=True),
    sa.Column('dribbles_attempted', sa.Integer(), nullable=True),
    sa.Column('dribbles_successful', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('clean_sheet', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('stat_id'),
    sa.UniqueConstraint('match_id', 'player_id', 'source', name='uq_player_match_stats_match_player_source')
    )
    op.create_index('idx_player_match_stats_match', 'player_match_stats', ['match_id'], unique=False)
    op.create_index('idx_player_match_stats_player', 'player_match_stats', ['player_id'], unique=False)
    op.create_index('idx_player_match_stats_team', 'player_match_stats', ['team_id'], unique=False)
    op.alter_column('betting_odds', 'odds_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('betting_odds', 'odds_home',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('betting_odds', 'odds_draw',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('betting_odds', 'odds_away',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('betting_odds', 'implied_prob_home',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('betting_odds', 'implied_prob_draw',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('betting_odds', 'implied_prob_away',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('betting_odds', 'collected_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('betting_odds', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_betting_odds_unique'), table_name='betting_odds')
    op.create_unique_constraint('uq_betting_odds_match_bookmaker', 'betting_odds', ['match_id', 'bookmaker'])
    op.alter_column('collection_logs', 'log_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('collection_logs', 'started_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('collection_logs', 'completed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('collection_logs', 'duration_seconds',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('collection_logs', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('fbref_collection_log', 'log_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('fbref_collection_log', 'started_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('fbref_collection_log', 'completed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('fbref_collection_log', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('head_to_head', 'h2h_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('head_to_head', 'last_updated',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_unique_constraint('uq_head_to_head_team_a_team_b', 'head_to_head', ['team_a_id', 'team_b_id'])
    op.alter_column('league_standings', 'standing_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('league_standings', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_unique_constraint('uq_league_standings_season_matchday_team', 'league_standings', ['season', 'matchday', 'team_id'])
    op.alter_column('match_events', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('match_events', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_foreign_key(None, 'match_events', 'players', ['player_id'], ['player_id'])
    op.alter_column('match_statistics', 'stat_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('match_statistics', 'possession_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('match_statistics', 'pass_accuracy_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('match_statistics', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('match_statistics', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_unique_constraint('uq_match_statistics_match_team', 'match_statistics', ['match_id', 'team_id'])
    op.alter_column('matches', 'match_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('matches', 'match_datetime',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('matches', 'result',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=True)
    op.alter_column('matches', 'temperature_celsius',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('matches', 'humidity_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('matches', 'wind_speed_kmh',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('matches', 'precipitation_mm',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('matches', 'weather_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('matches', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('matches', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('player_season_stats', 'stat_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('player_season_stats', 'pass_accuracy_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('player_season_stats', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_unique_constraint('uq_player_season_stats_player_team_season', 'player_season_stats', ['player_id', 'team_id', 'season'])
    op.alter_column('players', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('players', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('players', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('team_locations', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_locations', 'team_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('team_locations', 'lat',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('team_locations', 'lon',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('team_locations', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('team_ratings', 'rating_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('team_ratings', 'elo_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('team_ratings', 'pi_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('team_ratings', 'goals_scored_last_5',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('team_ratings', 'goals_conceded_last_5',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('team_ratings', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ux_team_ratings_team_match'), table_name='team_ratings')
    op.alter_column('teams', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('teams', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('teams', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ux_teams_name'), table_name='teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ux_teams_name'), 'teams', ['team_name'], unique=1)
    op.alter_column('teams', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('teams', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('teams', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('ux_team_ratings_team_match'), 'team_ratings', ['team_id', 'match_id'], unique=1)
    op.alter_column('team_ratings', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('team_ratings', 'goals_conceded_last_5',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('team_ratings', 'goals_scored_last_5',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('team_ratings', 'pi_rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('team_ratings', 'elo_rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('team_ratings', 'rating_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('team_locations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('team_locations', 'lon',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False)
    op.alter_column('team_locations', 'lat',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False)
    op.alter_column('team_locations', 'team_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('team_locations', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('players', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('players', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint('uq_player_season_stats_player_team_season', 'player_season_stats', type_='unique')
    op.alter_column('player_season_stats', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('player_season_stats', 'pass_accuracy_percent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('player_season_stats', 'stat_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('matches', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('matches', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('matches', 'weather_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('matches', 'precipitation_mm',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('matches', 'wind_speed_kmh',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('matches', 'humidity_percent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('matches', 'temperature_celsius',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('matches', 'result',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=True)
    op.alter_column('matches', 'match_datetime',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('matches', 'match_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint('uq_match_statistics_match_team', 'match_statistics', type_='unique')
    op.alter_column('match_statistics', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('match_statistics', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('match_statistics', 'pass_accuracy_percent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('match_statistics', 'possession_percent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('match_statistics', 'stat_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'match_events', type_='foreignkey')
    op.alter_column('match_events', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('match_events', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint('uq_league_standings_season_matchday_team', 'league_standings', type_='unique')
    op.alter_column('league_standings', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('league_standings', 'standing_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint('uq_head_to_head_team_a_team_b', 'head_to_head', type_='unique')
    op.alter_column('head_to_head', 'last_updated',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('head_to_head', 'h2h_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('fbref_collection_log', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('fbref_collection_log', 'completed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('fbref_collection_log', 'started_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('fbref_collection_log', 'log_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('collection_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('collection_logs', 'duration_seconds',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('collection_logs', 'completed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('collection_logs', 'started_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('collection_logs', 'log_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint('uq_betting_odds_match_bookmaker', 'betting_odds', type_='unique')
    op.create_index(op.f('idx_betting_odds_unique'), 'betting_odds', ['match_id', 'bookmaker'], unique=1)
    op.alter_column('betting_odds', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('betting_odds', 'collected_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('betting_odds', 'implied_prob_away',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('betting_odds', 'implied_prob_draw',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('betting_odds', 'implied_prob_home',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('betting_odds', 'odds_away',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('betting_odds', 'odds_draw',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('betting_odds', 'odds_home',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('betting_odds', 'odds_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('idx_player_match_stats_team', table_name='player_match_stats')
    op.drop_index('idx_player_match_stats_player', table_name='player_match_stats')
    op.drop_index('idx_player_match_stats_match', table_name='player_match_stats')
    op.drop_table('player_match_stats')
    op.drop_index('idx_advanced_stats_team', table_name='advanced_match_stats')
    op.drop_index('idx_advanced_stats_match', table_name='advanced_match_stats')
    op.drop_table('advanced_match_stats')
    # ### end Alembic commands ###
